name: Validate families.json

on:
  pull_request:
    branches:
      - gh-pages
    paths:
      - "families.json"

jobs:
  build:
    name: Validate families.json
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npm test -- families
